name: My Learning  with Environment Variables

on: push

jobs:
  my-job:
    name: Learning Jobs
    runs-on: ubuntu-latest
    steps:
    - name: Print a message
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Indresh
        MIDDLE_NAME: VP
        LAST_NAME: Pandey
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
